### PR TITLE
what i need to add

### PR DESCRIPTION
**Pull request by satwantsingh007**

### CODE REVIEW

**Review by muditbhadouria — COMMENTED** [review]
You don't need to apply it on the table. You should apply it on every row

**Comment by satwantsingh007** [comment]
> You don't need to apply it to the table. You should apply it on every row

but in this file, there are separate column of positive and negative, where is the row

**Comment by muditbhadouria** [comment]
Please go through the documentation of angular material table. It will be more clear.

**Comment by muditbhadouria** [comment]
Closing

**Pull request closed without merging**
